const DASHBOARD_HTML = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>LLM Stream Watchdog</title>
  <style>
    :root{color-scheme:dark;--bg:#121212;--surface:#1a1a1a;--surface-2:#202020;--surface-3:#242424;--border:#2e2e2e;--border-strong:#393939;--text:#fafafa;--muted:#898989;--soft:#b4b4b4;--green:#3ecf8e;--green-dim:#1f4b37;--amber:#f5b942;--red:#ef6461}
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}
    button,select{font:inherit}button:focus-visible,select:focus-visible{outline:2px solid var(--green);outline-offset:2px}.shell{min-height:100vh}.topbar{height:64px;border-bottom:1px solid var(--border);background:#121212e8;backdrop-filter:blur(12px);position:sticky;top:0;z-index:10}.topbar-inner{max-width:1240px;height:100%;margin:auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:11px;min-width:0}.logo{width:28px;height:28px;border:1px solid #3ecf8e66;border-radius:7px;background:#16372a;display:grid;place-items:center;box-shadow:inset 0 0 0 1px #ffffff08}.logo svg{width:17px;height:17px;fill:none;stroke:var(--green);stroke-width:1.8}.brand-copy{display:flex;align-items:baseline;gap:9px;min-width:0}.brand h1{font-size:14px;line-height:1;font-weight:600;letter-spacing:-.01em;margin:0;white-space:nowrap}.brand small{color:var(--muted);font:11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace}.live{display:flex;align-items:center;gap:8px;color:var(--soft);font-size:12px;white-space:nowrap}.live-dot{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px #3ecf8e18}.live.error .live-dot{background:var(--red);box-shadow:0 0 0 4px #ef646118}.live.error{color:var(--red)}
    main{max-width:1240px;margin:auto;padding:32px 24px 56px}.page-head{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:24px}.eyebrow{color:var(--green);font:600 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase}.page-head h2{font-size:24px;line-height:1.25;font-weight:500;letter-spacing:-.025em;margin:7px 0 4px}.page-head p{margin:0;color:var(--muted);font-size:13px}.controls{display:flex;align-items:center;gap:8px}.control{height:34px;border:1px solid var(--border-strong);background:var(--surface);color:var(--soft);border-radius:7px;padding:0 11px}.control:hover{border-color:#4d4d4d;color:var(--text)}button.control{cursor:pointer}.updated{margin-left:5px;color:var(--muted);font:11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap}
    .overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--border);border-radius:9px;overflow:hidden;background:var(--surface);margin-bottom:16px}.hero-metric{min-height:126px;padding:20px;border-right:1px solid var(--border);position:relative}.hero-metric:last-child{border-right:0}.hero-label{color:var(--muted);font-size:12px}.hero-value{font-size:31px;line-height:1.15;font-weight:500;letter-spacing:-.035em;margin-top:10px}.hero-meta{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:11px;margin-top:10px}.signal{width:6px;height:6px;border-radius:50%;background:var(--soft)}.hero-metric.good .hero-value{color:var(--green)}.hero-metric.good .signal{background:var(--green)}.hero-metric.warn .hero-value{color:var(--amber)}.hero-metric.warn .signal{background:var(--amber)}.hero-metric.bad .hero-value{color:var(--red)}.hero-metric.bad .signal{background:var(--red)}
    .secondary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:16px}.mini{border:1px solid var(--border);border-radius:8px;background:var(--surface);padding:13px 14px;display:flex;align-items:center;justify-content:space-between;gap:12px}.mini span{color:var(--muted);font-size:12px}.mini b{font:500 16px/1 ui-monospace,SFMono-Regular,Menlo,monospace}.mini.warn b{color:var(--amber)}.mini.bad b{color:var(--red)}
    .content-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(340px,.85fr);gap:16px}.panel{border:1px solid var(--border);border-radius:9px;background:var(--surface);overflow:hidden}.panel-wide{grid-column:1/-1}.panel-head{height:52px;padding:0 16px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;gap:16px}.panel-title{display:flex;align-items:center;gap:9px}.panel-title h3{font-size:13px;font-weight:500;margin:0}.panel-title small{color:var(--muted);font-size:11px}.panel-icon{width:24px;height:24px;border:1px solid var(--border);border-radius:6px;display:grid;place-items:center;color:var(--muted);font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.panel-body{padding:18px}.latency-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--border);border:1px solid var(--border);border-radius:7px;overflow:hidden}.latency-cell{background:var(--surface-2);padding:15px}.latency-cell small{display:block;color:var(--muted);font-size:11px;margin-bottom:7px}.latency-cell b{font:500 18px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace}.latency-cell:nth-child(n+4) b{color:var(--soft)}
    .chart-wrap{height:214px;display:flex;flex-direction:column}.chart{flex:1;position:relative;display:flex;align-items:flex-end;gap:3px;padding:10px 2px 0;border-bottom:1px solid var(--border)}.chart:before,.chart:after{content:"";position:absolute;left:0;right:0;border-top:1px dashed #2e2e2e;pointer-events:none}.chart:before{top:33%}.chart:after{top:66%}.column{flex:1;min-width:2px;height:100%;display:flex;align-items:flex-end;justify-content:center;position:relative;z-index:1}.bar{width:min(26px,72%);min-height:2px;border-radius:3px 3px 0 0;background:var(--amber);opacity:.85}.bar.zero{background:#393939;opacity:1}.axis{display:flex;gap:3px;padding:8px 2px 0}.axis span{flex:1;min-width:2px;text-align:center;color:var(--muted);font:9px/1 ui-monospace,SFMono-Regular,Menlo,monospace}.chart-empty{height:100%;display:grid;place-items:center;color:var(--muted);font-size:12px}
    .health-empty{min-height:190px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:28px}.check{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:var(--green-dim);border:1px solid #3ecf8e55;color:var(--green);font-size:20px;margin-bottom:13px}.health-empty strong{font-size:14px;font-weight:500}.health-empty p{color:var(--muted);font-size:12px;margin:5px 0 0}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:11px 14px;border-bottom:1px solid var(--border);white-space:nowrap}th{color:var(--muted);font-size:10px;font-weight:500;text-transform:uppercase;letter-spacing:.07em;background:var(--surface-2)}td{color:var(--soft)}tbody tr:hover{background:var(--surface-2)}tbody tr:last-child td{border-bottom:0}code{color:var(--red);font:11px ui-monospace,SFMono-Regular,Menlo,monospace}.event-reason{max-width:280px;overflow:hidden;text-overflow:ellipsis}.privacy{margin-top:16px;display:flex;align-items:center;gap:8px;color:var(--muted);font-size:11px}.privacy svg{width:13px;height:13px;stroke:var(--muted);fill:none;stroke-width:1.8}
    @media(max-width:900px){.overview{grid-template-columns:repeat(2,1fr)}.hero-metric:nth-child(2){border-right:0}.hero-metric:nth-child(-n+2){border-bottom:1px solid var(--border)}.secondary{grid-template-columns:repeat(2,1fr)}.content-grid{grid-template-columns:1fr}.panel-wide{grid-column:auto}.updated{display:none}}
    @media(max-width:600px){.topbar-inner,main{padding-left:16px;padding-right:16px}.brand small{display:none}.page-head{display:block}.controls{margin-top:18px}.overview{grid-template-columns:1fr 1fr}.hero-metric{padding:16px;min-height:112px}.hero-value{font-size:26px}.secondary{grid-template-columns:1fr 1fr}.latency-grid{grid-template-columns:repeat(2,1fr)}.panel-head{height:auto;min-height:52px;padding:10px 14px}.topbar .live span:last-child{display:none}}
  </style>
</head>
<body><div class="shell">
<header class="topbar"><div class="topbar-inner"><div class="brand"><div class="logo"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h3l2-6 4 12 2-6h5"/></svg></div><div class="brand-copy"><h1>LLM Stream Watchdog</h1><small>localhost:8787</small></div></div><div class="live" id="status" role="status" aria-live="polite"><span class="live-dot"></span><span>正在连接</span></div></div></header>
<main><section class="page-head"><div><div class="eyebrow">Observability</div><h2>上游稳定性</h2><p>只记录匿名生命周期元数据，不读取对话内容。</p></div><div class="controls"><select class="control" id="days" aria-label="时间范围"><option value="1">24 小时</option><option value="7">7 天</option><option value="30" selected>30 天</option></select><button class="control" id="refresh">刷新</button><span class="updated" id="updated">—</span></div></section>
<section class="overview" id="overview"></section><section class="secondary" id="secondary"></section>
<section class="content-grid"><article class="panel"><div class="panel-head"><div class="panel-title"><span class="panel-icon">ms</span><div><h3>响应延迟</h3><small>首字节与请求总耗时</small></div></div></div><div class="panel-body"><div class="latency-grid" id="latency"></div></div></article>
<article class="panel"><div class="panel-head"><div class="panel-title"><span class="panel-icon">↗</span><div><h3>每日异常趋势</h3><small>仅上游重试、停滞与失败</small></div></div></div><div class="panel-body"><div class="chart-wrap"><div class="chart" id="bars" role="img" aria-label="每日异常趋势图"></div><div class="axis" id="axis"></div></div></div></article>
<article class="panel panel-wide"><div class="panel-head"><div class="panel-title"><span class="panel-icon">!</span><div><h3>最近异常</h3><small>客户端主动取消不属于异常</small></div></div><small id="anomaly-count">0 events</small></div><div id="anomalies"></div></article></section>
<div class="privacy"><svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><span>不保存 prompt、响应正文、API Key 或 Authorization · 历史最多保留 30 天 · 每 15 秒刷新</span></div></main>
</div><script>
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':n>=1000?(n/1000).toFixed(1)+'s':Math.round(n)+'ms';
const metric=(label,value,meta,cls='')=>'<div class="hero-metric '+cls+'"><div class="hero-label">'+label+'</div><div class="hero-value">'+value+'</div><div class="hero-meta"><span class="signal"></span>'+meta+'</div></div>';
const mini=(label,value,cls='')=>'<div class="mini '+cls+'"><span>'+label+'</span><b>'+value+'</b></div>';
async function load(){const days=document.querySelector('#days').value;try{const r=await fetch('/api/dashboard?days='+days,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json(),t=d.totals;const criticalTotal=t.streamStalls+t.failures;const anomalyTotal=t.retries+criticalTotal;const expected=Math.max(0,t.requests-t.cancelled);const completion=expected?Math.min(100,Math.round(t.completed/expected*100)):100;
 document.querySelector('#status').className='live';document.querySelector('#status').innerHTML='<span class="live-dot"></span><span>运行正常</span>';
 document.querySelector('#overview').innerHTML=metric('请求',t.requests,'所选时间范围')+metric('完成率',completion+'%','完成 '+t.completed+' / '+expected+(t.cancelled?' · 已排除取消':''),completion===100?'good':completion>=95?'warn':'bad')+metric('自动恢复',t.recoveredAfterRetry,t.retries?('共 '+t.retries+' 次重试'):'未触发重试',t.retries?'warn':'good')+metric('上游异常',anomalyTotal,criticalTotal?(criticalTotal+' 个未恢复异常'):t.retries?'均已自动恢复':'上游状态健康',criticalTotal?'bad':t.retries?'warn':'good');
 document.querySelector('#secondary').innerHTML=mini('首字节超时',t.firstByteTimeouts,t.firstByteTimeouts?'warn':'')+mini('流中途停滞',t.streamStalls,t.streamStalls?'bad':'')+mini('最终失败',t.failures,t.failures?'bad':'')+mini('客户端取消',t.cancelled);
 const l=d.latency;document.querySelector('#latency').innerHTML=[['首字节 P50',l.firstByteP50Ms],['首字节 P95',l.firstByteP95Ms],['首字节最大',l.firstByteMaxMs],['总耗时 P50',l.durationP50Ms],['总耗时 P95',l.durationP95Ms],['总耗时最大',l.durationMaxMs]].map(x=>'<div class="latency-cell"><small>'+x[0]+'</small><b>'+fmt(x[1])+'</b></div>').join('');
 const max=Math.max(1,...d.daily.map(x=>x.anomalies));document.querySelector('#bars').innerHTML=d.daily.length?d.daily.map(x=>'<div class="column" title="'+esc(x.date)+' · '+x.anomalies+' 个异常 / '+x.requests+' 个请求"><div class="bar '+(x.anomalies?'':'zero')+'" style="height:'+Math.max(2,x.anomalies/max*100)+'%"></div></div>').join(''):'<div class="chart-empty">暂无数据</div>';document.querySelector('#axis').innerHTML=d.daily.map((x,i)=>'<span>'+((d.daily.length>14&&i%5)?'':esc(x.date.slice(5)))+'</span>').join('');
 document.querySelector('#anomaly-count').textContent=d.recentAnomalies.length+' 条事件';document.querySelector('#anomalies').innerHTML=d.recentAnomalies.length?'<div class="table-scroll"><table><thead><tr><th>时间</th><th>事件</th><th>原因</th><th>尝试</th><th>路径</th></tr></thead><tbody>'+d.recentAnomalies.map(x=>'<tr><td>'+esc(new Date(x.time).toLocaleString())+'</td><td><code>'+esc(x.event)+'</code></td><td class="event-reason">'+esc(x.reason)+'</td><td>'+esc(x.attempt)+'</td><td>'+esc(x.path)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="health-empty"><div class="check">✓</div><strong>所选时间范围内没有异常</strong><p>客户端取消会单独统计，不会影响健康状态。</p></div>';
 document.querySelector('#updated').textContent='更新 '+new Date(d.generatedAt).toLocaleTimeString();
 }catch(e){const s=document.querySelector('#status');s.className='live error';s.innerHTML='<span class="live-dot"></span><span>面板不可用</span>';}}
document.querySelector('#refresh').onclick=load;document.querySelector('#days').onchange=load;load();setInterval(load,15000);
</script></body></html>`;

function send(response, status, type, body) {
  response.statusCode = status;
  response.setHeader('content-type', type);
  response.setHeader('cache-control', 'no-store');
  response.setHeader('x-content-type-options', 'nosniff');
  response.setHeader('x-frame-options', 'DENY');
  response.setHeader('referrer-policy', 'no-referrer');
  response.setHeader('content-security-policy', "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'");
  response.end(body);
}

export function handleDashboardRequest(request, response, { store, config }) {
  const url = new URL(request.url || '/', 'http://localhost');
  if (request.method === 'GET' && (url.pathname === '/dashboard' || url.pathname === '/dashboard/')) {
    send(response, 200, 'text/html; charset=utf-8', DASHBOARD_HTML);
    return true;
  }
  if (request.method === 'GET' && url.pathname === '/api/dashboard') {
    const summary = store.summary(url.searchParams.get('days'));
    summary.runtime = {
      upstreamConfigured: true,
      retentionDays: config.eventRetentionDays,
      streamingFirstByteTimeoutMs: config.firstByteTimeoutMs,
      nonStreamingFirstByteTimeoutMs: config.nonStreamingFirstByteTimeoutMs,
      idleTimeoutMs: config.idleTimeoutMs,
      maxAttempts: config.maxAttempts,
    };
    send(response, 200, 'application/json; charset=utf-8', JSON.stringify(summary));
    return true;
  }
  return false;
}
